# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('logcreattime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=20)),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='deployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('creattime', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=12)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=100)),
                ('creattime', models.DateTimeField()),
                ('logintime', models.DateTimeField()),
                ('loginIp', models.GenericIPAddressField(unpack_ipv4=True)),
                ('isActive', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
                ('middle', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('privateip', models.GenericIPAddressField()),
                ('internetip', models.GenericIPAddressField()),
                ('buytime', models.DateField()),
                ('position', models.CharField(max_length=120)),
                ('usecase', models.NullBooleanField()),
                ('configurinfo', models.TextField()),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=120)),
                ('headImg', models.FileField(upload_to='./upload/')),
            ],
        ),
    ]
