# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('filepath', models.CharField(max_length=200)),
                ('uploadtime', models.DateTimeField()),
            ],
        ),
    ]
