# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=100)),
                ('creattime', models.DateTimeField()),
                ('logintime', models.DateTimeField()),
                ('loginIp', models.GenericIPAddressField(unpack_ipv4=True)),
                ('isActive', models.NullBooleanField()),
            ],
        ),
    ]
