# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('privateip', models.GenericIPAddressField()),
                ('internetip', models.GenericIPAddressField()),
                ('buytime', models.DateField()),
                ('position', models.CharField(max_length=120)),
                ('usecase', models.NullBooleanField()),
                ('configurinfo', models.TextField()),
                ('remark', models.TextField()),
            ],
        ),
    ]
